### PR TITLE
Purpose readme contribution

### PR DESCRIPTION
**Pull request by cbracco**
Thanks for doing part B, @DevonAero! I am going to merge this into my branch, review for typos etc, then I’ll ping you so we can both do a final review and I will submit the pull request to the HubSpot repository.

### CODE REVIEW

**Comment by DevinHarris** [comment]
Hey @cbracco! Looks like QA is down, so I'm shooting you a message on here!

Thanks for the edits and looks awesome dude! How should we both go about submitting? Not sure if we're suppose to merge them together because I think we're suppose to do the pull request separately from different branches so we both get credit. 

Let me know what you think, and thanks again!

**Comment by cbracco** [comment]
@DevonAero Since we each have commits included on this branch now, we should both get credit (at least I think so!). I wouldn’t want to bombard them with two pull requests to simply update the README... haha. Is that okay with you? If so, I can go ahead and submit the pull request. 

Hopefully they accept our changes! :+1:

**Comment by DevinHarris** [comment]
Haha I agree :). I think the reason they want us to submit separately is because it would credit both our GitHub profiles.

> Having your pull request accepted by the owner of the repository would be quite impressive, and would give your GitHub account a huge boost, considering the major technology you contribute to will show up on your GitHub profile as a “Repositories contributed to.”

 Also they gave us different pull request descriptions in the course. Mine would be:.

> Option B Pull Request Description
> To make technologyRepo more approachable to a larger number of users—from informed developers to curious passersby and new and interested visitors—I have added a new section to the technologyRepo README. The section is entitled What to Use technologyRepo for and When to Use It. As the name suggests, the new section, a brief paragraph, explains in plain and straightforward language what technologyRepo is used for and when one should use it.
> 
> Other repositories may begin to use this new informative and catchy section soon, as my colleagues contact open-source technologies in an effort to make them more accessible to the tens of thousands of new users learning to code and thousands joining GitHub every day.

If it automatically does that with the merge, then I think everything good to go! Is that cool? 

I have a limited knowledge with GitHub, outside of simply pushing things so your way might be best.

**Comment by cbracco** [comment]
@DevonAero Okay, let’s give it a shot. Submitting now!

**Comment by cbracco** [comment]
@DevonAero submitted! https://github.com/HubSpot/tether/pull/149

**Comment by DevinHarris** [comment]
Thanks man, you did a great job! Is there anyway I can get Tether to show up under my 'Projects Contributed to' also?

**Comment by cbracco** [comment]
@DevonAero It seems its based on who the owner of pull request is, and doesn’t take into account that commits from other users might be included in that request. Which means I was wrong. You were correct.

Shit. I’m sorry!

One quick way to get it added is to submit your own pull request, but change something small in the README like grammar, add/remove a sentence, etc. They were super-fast at approving the last pull request, maybe you can get one through quickly, too. Then it should show up under your "Projects Contributed to" section on your GitHub profile.

Again, I am sorry for screwing that up. You deserve the credit too, of course!

**Comment by DevinHarris** [comment]
Haha no worries dude, it's cool! I actually had an idea for something to add. Should I post a comment letting them know?

**Comment by cbracco** [comment]
Oh good! You can include a description with your pull request, I would just include the comment in there.

**Comment by DevinHarris** [comment]
Just sent it! Thanks again dude, it was great working with you!

**Pull request merged**
